/**
 * ============================================================================
 * QDRANT MEMORY SERVICE
 * ============================================================================
 * 
 * This service provides VECTOR MEMORY storage using Qdrant, enabling
 * SEMANTIC SEARCH across story elements. It's the "long-term memory" that
 * helps agents find relevant context when generating new content.
 * 
 * WHAT IS VECTOR MEMORY?
 * ----------------------
 * Traditional databases search by exact matches (SQL WHERE clauses).
 * Vector databases search by MEANING using embeddings:
 * 
 *   1. TEXT → EMBEDDING: Convert text to a vector of numbers (e.g., 1536 floats)
 *   2. STORE: Save the vector in Qdrant with metadata
 *   3. SEARCH: Convert query to vector, find similar vectors
 * 
 * Example:
 *   Query: "brave warrior with a tragic past"
 *   Finds: Character "Kira" who is described as "a fearless soldier haunted by loss"
 *   (Even though the words are different, the MEANING is similar!)
 * 
 * WHY QDRANT?
 * -----------
 * Qdrant is a high-performance vector database that:
 *   - Handles millions of vectors efficiently
 *   - Supports filtering (e.g., only search within a project)
 *   - Has a simple REST API and JavaScript client
 *   - Can run locally or in the cloud
 * 
 * COLLECTIONS:
 * ------------
 * Data is organized into three collections:
 * 
 *   1. manoe_characters
 *      - Stores character profiles
 *      - Searchable by traits, motivations, backstory
 *      - Used by Writer to find relevant characters for scenes
 * 
 *   2. manoe_worldbuilding
 *      - Stores world elements (locations, cultures, rules)
 *      - Searchable by type and description
 *      - Used by Writer to maintain world consistency
 * 
 *   3. manoe_scenes
 *      - Stores generated scene content
 *      - Searchable by content and summary
 *      - Used for continuity and avoiding repetition
 * 
 * EMBEDDING PROVIDERS:
 * --------------------
 * Embeddings can be generated by different providers (priority order):
 * 
 *   1. OPENAI (text-embedding-3-small)
 *      - 1536 dimensions
 *      - Best quality, requires API key
 *      - ~$0.02 per 1M tokens
 * 
 *   2. GEMINI (embedding-001)
 *      - 768 dimensions
 *      - Good quality, requires Google API key
 *      - Free tier available
 * 
 *   3. LOCAL (fallback)
 *      - 384 dimensions
 *      - Random vectors (placeholder for local model)
 *      - No API key needed, but poor quality
 * 
 * USAGE FLOW:
 * -----------
 * 
 *   STORING:
 *   --------
 *   1. ProfilerAgent creates character → storeCharacter(projectId, character)
 *   2. Character text is converted to embedding
 *   3. Embedding + metadata stored in Qdrant
 * 
 *   SEARCHING:
 *   ----------
 *   1. WriterAgent needs context → searchCharacters(projectId, "scene about battle")
 *   2. Query converted to embedding
 *   3. Qdrant finds similar character embeddings
 *   4. Returns top 3 most relevant characters
 * 
 * PROJECT ISOLATION:
 * ------------------
 * All operations are filtered by projectId to ensure:
 *   - User A's characters don't appear in User B's searches
 *   - Each project has its own "memory space"
 * 
 * EXAMPLE:
 * --------
 *   // Store a character
 *   await qdrantMemory.storeCharacter(projectId, {
 *     name: "Kira",
 *     archetype: "Warrior",
 *     coreMotivation: "Protect the innocent",
 *     psychologicalWound: "Lost her family in the war"
 *   });
 * 
 *   // Later, find relevant characters for a battle scene
 *   const characters = await qdrantMemory.searchCharacters(
 *     projectId,
 *     "fierce combat with emotional stakes",
 *     3  // top 3 results
 *   );
 *   // Returns Kira because her profile matches the query semantically
 * 
 * @see StorytellerOrchestrator.ts for how memory is used during generation
 * @see WriterAgent.ts for context retrieval before drafting
 */

import { Service } from "@tsed/di";
import { QdrantClient } from "@qdrant/js-client-rest";
import OpenAI from "openai";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { v4 as uuidv4 } from "uuid";

/**
 * Embedding provider types
 */
export enum EmbeddingProvider {
  OPENAI = "openai",
  GEMINI = "gemini",
  LOCAL = "local",
}

/**
 * Embedding provider info
 */
export interface EmbeddingProviderInfo {
  providerType: EmbeddingProvider;
  modelName: string;
  dimension: number;
}

/**
 * Search result structure
 */
export interface SearchResult<T> {
  id: string;
  score: number;
  payload: T;
}

/**
 * Character payload
 */
export interface CharacterPayload {
  projectId: string;
  character: Record<string, unknown>;
  name: string;
  createdAt: string;
  [key: string]: unknown;
}

/**
 * Worldbuilding payload
 */
export interface WorldbuildingPayload {
  projectId: string;
  elementType: string;
  element: Record<string, unknown>;
  createdAt: string;
  [key: string]: unknown;
}

/**
 * Scene payload
 */
export interface ScenePayload {
  projectId: string;
  sceneNumber: number;
  scene: Record<string, unknown>;
  createdAt: string;
  [key: string]: unknown;
}

@Service()
export class QdrantMemoryService {
  private client: QdrantClient | null = null;
  private openaiClient: OpenAI | null = null;
  private geminiClient: GoogleGenerativeAI | null = null;
  private embeddingProvider: EmbeddingProvider = EmbeddingProvider.LOCAL;
  private embeddingDimension: number = 384;
  private embeddingModel: string = "all-MiniLM-L6-v2";

  // Collection names
  private readonly COLLECTION_CHARACTERS = "manoe_characters";
  private readonly COLLECTION_WORLDBUILDING = "manoe_worldbuilding";
  private readonly COLLECTION_SCENES = "manoe_scenes";

  /**
   * Connect to Qdrant and initialize embedding provider
   * 
   * @param openaiApiKey - OpenAI API key for embeddings (highest priority)
   * @param geminiApiKey - Gemini API key for embeddings (second priority)
   * @param preferLocal - If true, use local embeddings even if API keys available
   */
  async connect(
    openaiApiKey?: string,
    geminiApiKey?: string,
    preferLocal: boolean = false
  ): Promise<void> {
    const qdrantUrl = process.env.QDRANT_URL || "http://localhost:6333";
    const qdrantApiKey = process.env.QDRANT_API_KEY;

    this.client = new QdrantClient({
      url: qdrantUrl,
      apiKey: qdrantApiKey,
    });

    // Initialize embedding provider
    if (!preferLocal && openaiApiKey) {
      this.openaiClient = new OpenAI({ apiKey: openaiApiKey });
      this.embeddingProvider = EmbeddingProvider.OPENAI;
      this.embeddingDimension = 1536;
      this.embeddingModel = "text-embedding-3-small";
      console.log("Qdrant Memory: Using OpenAI embeddings (1536 dimensions)");
    } else if (!preferLocal && geminiApiKey) {
      this.geminiClient = new GoogleGenerativeAI(geminiApiKey);
      this.embeddingProvider = EmbeddingProvider.GEMINI;
      this.embeddingDimension = 768;
      this.embeddingModel = "embedding-001";
      console.log("Qdrant Memory: Using Gemini embeddings (768 dimensions)");
    } else {
      this.embeddingProvider = EmbeddingProvider.LOCAL;
      this.embeddingDimension = 384;
      this.embeddingModel = "all-MiniLM-L6-v2";
      console.log("Qdrant Memory: Using local embeddings (384 dimensions)");
    }

    // Ensure collections exist
    await this.ensureCollections();

    console.log(`Qdrant Memory connected to ${qdrantUrl}`);
  }

  /**
   * Get embedding provider info
   */
  get providerInfo(): EmbeddingProviderInfo {
    return {
      providerType: this.embeddingProvider,
      modelName: this.embeddingModel,
      dimension: this.embeddingDimension,
    };
  }

  /**
   * Ensure all required collections exist
   */
  private async ensureCollections(): Promise<void> {
    if (!this.client) return;

    const collections = [
      this.COLLECTION_CHARACTERS,
      this.COLLECTION_WORLDBUILDING,
      this.COLLECTION_SCENES,
    ];

    for (const collectionName of collections) {
      try {
        await this.client.getCollection(collectionName);
      } catch (error) {
        // Collection doesn't exist, create it
        await this.client.createCollection(collectionName, {
          vectors: {
            size: this.embeddingDimension,
            distance: "Cosine",
          },
        });
        console.log(`Created Qdrant collection: ${collectionName}`);
      }
    }
  }

  /**
   * Generate embedding for text
   */
  private async generateEmbedding(text: string): Promise<number[]> {
    if (this.embeddingProvider === EmbeddingProvider.OPENAI && this.openaiClient) {
      const response = await this.openaiClient.embeddings.create({
        model: this.embeddingModel,
        input: text,
      });
      return response.data[0].embedding;
    } else if (this.embeddingProvider === EmbeddingProvider.GEMINI && this.geminiClient) {
      const model = this.geminiClient.getGenerativeModel({ model: "embedding-001" });
      const result = await model.embedContent(text);
      return result.embedding.values;
    } else {
      // Local embeddings - return random vector for now
      // In production, use a local embedding model like fastembed
      return Array.from({ length: this.embeddingDimension }, () => Math.random() - 0.5);
    }
  }

  /**
   * Store a character in Qdrant
   */
  async storeCharacter(
    projectId: string,
    character: Record<string, unknown>
  ): Promise<string> {
    if (!this.client) throw new Error("Qdrant client not connected");

    const characterName = String(character.name ?? "Unknown");
    const characterText = this.characterToText(character);
    const embedding = await this.generateEmbedding(characterText);

    const pointId = uuidv4();
    const payload: CharacterPayload = {
      projectId,
      character,
      name: characterName,
      createdAt: new Date().toISOString(),
    };

    await this.client.upsert(this.COLLECTION_CHARACTERS, {
      points: [
        {
          id: pointId,
          vector: embedding,
          payload: payload as Record<string, unknown>,
        },
      ],
    });

    return pointId;
  }

  /**
   * Search for characters by semantic similarity
   */
  async searchCharacters(
    projectId: string,
    query: string,
    limit: number = 3
  ): Promise<SearchResult<CharacterPayload>[]> {
    if (!this.client) return [];

    const queryEmbedding = await this.generateEmbedding(query);

    const results = await this.client.search(this.COLLECTION_CHARACTERS, {
      vector: queryEmbedding,
      limit,
      filter: {
        must: [{ key: "projectId", match: { value: projectId } }],
      },
    });

    return results.map((result) => ({
      id: String(result.id),
      score: result.score,
      payload: result.payload as CharacterPayload,
    }));
  }

  /**
   * Get all characters for a project
   */
  async getProjectCharacters(projectId: string): Promise<CharacterPayload[]> {
    if (!this.client) return [];

    const results = await this.client.scroll(this.COLLECTION_CHARACTERS, {
      filter: {
        must: [{ key: "projectId", match: { value: projectId } }],
      },
      limit: 100,
    });

    return results.points.map((point) => point.payload as CharacterPayload);
  }

  /**
   * Store worldbuilding element in Qdrant
   */
  async storeWorldbuilding(
    projectId: string,
    elementType: string,
    element: Record<string, unknown>
  ): Promise<string> {
    if (!this.client) throw new Error("Qdrant client not connected");

    const elementText = this.worldbuildingToText(elementType, element);
    const embedding = await this.generateEmbedding(elementText);

    const pointId = uuidv4();
    const payload: WorldbuildingPayload = {
      projectId,
      elementType,
      element,
      createdAt: new Date().toISOString(),
    };

    await this.client.upsert(this.COLLECTION_WORLDBUILDING, {
      points: [
        {
          id: pointId,
          vector: embedding,
          payload: payload as Record<string, unknown>,
        },
      ],
    });

    return pointId;
  }

  /**
   * Search for worldbuilding elements by semantic similarity
   */
  async searchWorldbuilding(
    projectId: string,
    query: string,
    limit: number = 5
  ): Promise<SearchResult<WorldbuildingPayload>[]> {
    if (!this.client) return [];

    const queryEmbedding = await this.generateEmbedding(query);

    const results = await this.client.search(this.COLLECTION_WORLDBUILDING, {
      vector: queryEmbedding,
      limit,
      filter: {
        must: [{ key: "projectId", match: { value: projectId } }],
      },
    });

    return results.map((result) => ({
      id: String(result.id),
      score: result.score,
      payload: result.payload as WorldbuildingPayload,
    }));
  }

  /**
   * Store a scene in Qdrant
   */
  async storeScene(
    projectId: string,
    sceneNumber: number,
    scene: Record<string, unknown>
  ): Promise<string> {
    if (!this.client) throw new Error("Qdrant client not connected");

    const sceneText = this.sceneToText(scene);
    const embedding = await this.generateEmbedding(sceneText);

    const pointId = uuidv4();
    const payload: ScenePayload = {
      projectId,
      sceneNumber,
      scene,
      createdAt: new Date().toISOString(),
    };

    await this.client.upsert(this.COLLECTION_SCENES, {
      points: [
        {
          id: pointId,
          vector: embedding,
          payload: payload as Record<string, unknown>,
        },
      ],
    });

    return pointId;
  }

  /**
   * Search for scenes by semantic similarity
   */
  async searchScenes(
    projectId: string,
    query: string,
    limit: number = 2
  ): Promise<SearchResult<ScenePayload>[]> {
    if (!this.client) return [];

    const queryEmbedding = await this.generateEmbedding(query);

    const results = await this.client.search(this.COLLECTION_SCENES, {
      vector: queryEmbedding,
      limit,
      filter: {
        must: [{ key: "projectId", match: { value: projectId } }],
      },
    });

    return results.map((result) => ({
      id: String(result.id),
      score: result.score,
      payload: result.payload as ScenePayload,
    }));
  }

  /**
   * Delete all data for a project
   */
  async deleteProjectData(projectId: string): Promise<void> {
    if (!this.client) return;

    const collections = [
      this.COLLECTION_CHARACTERS,
      this.COLLECTION_WORLDBUILDING,
      this.COLLECTION_SCENES,
    ];

    for (const collection of collections) {
      await this.client.delete(collection, {
        filter: {
          must: [{ key: "projectId", match: { value: projectId } }],
        },
      });
    }
  }

  /**
   * Convert character to searchable text
   */
  private characterToText(character: Record<string, unknown>): string {
    const parts: string[] = [];
    
    if (character.name) parts.push(`Name: ${character.name}`);
    if (character.archetype) parts.push(`Archetype: ${character.archetype}`);
    if (character.role) parts.push(`Role: ${character.role}`);
    if (character.coreMotivation) parts.push(`Motivation: ${character.coreMotivation}`);
    if (character.psychologicalWound) parts.push(`Wound: ${character.psychologicalWound}`);
    if (character.innerTrap) parts.push(`Inner Trap: ${character.innerTrap}`);
    if (character.backstory) parts.push(`Backstory: ${character.backstory}`);
    if (character.visualSignature) parts.push(`Visual: ${character.visualSignature}`);

    return parts.join(". ");
  }

  /**
   * Convert worldbuilding element to searchable text
   */
  private worldbuildingToText(
    elementType: string,
    element: Record<string, unknown>
  ): string {
    const parts: string[] = [`Type: ${elementType}`];

    if (element.name) parts.push(`Name: ${element.name}`);
    if (element.description) parts.push(`Description: ${element.description}`);
    if (element.location) parts.push(`Location: ${element.location}`);
    if (element.significance) parts.push(`Significance: ${element.significance}`);

    return parts.join(". ");
  }

  /**
   * Convert scene to searchable text
   */
  private sceneToText(scene: Record<string, unknown>): string {
    const parts: string[] = [];

    if (scene.sceneNumber) parts.push(`Scene ${scene.sceneNumber}`);
    if (scene.title) parts.push(`Title: ${scene.title}`);
    if (scene.setting) parts.push(`Setting: ${scene.setting}`);
    if (scene.summary) parts.push(`Summary: ${scene.summary}`);
    if (scene.content) {
      const content = String(scene.content);
      parts.push(`Content: ${content.substring(0, 500)}`);
    }

    return parts.join(". ");
  }

  /**
   * Disconnect from Qdrant
   */
  async disconnect(): Promise<void> {
    this.client = null;
    this.openaiClient = null;
    this.geminiClient = null;
  }
}
